[project]
name = "lynora"
version = "0.1.0"
authors = ["LYNORA Team"]

[application]
bytecode = "target/wasm32-unknown-unknown/release/lynora.wasm"
service_bytecode = "target/wasm32-unknown-unknown/release/lynora_service.wasm"

[dependencies]



